export const LOGIN_ACTIONS = {
    CLEAR_LOGIN_DATA: "CLEAR_LOGIN_DATA",
    LOGIN: "LOGIN",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGIN_SUCCESSFUL: "LOGIN_SUCCESSFUL",
    SET_USERNAME_AND_PASSWORD: "SET_USERNAME_AND_PASSWORD",
}
