export const WALL_ACTIONS = {
    POST_NEW_POST: "POST_NEW_POST",
    POST_NEW_COMMENT: "POST_NEW_COMMENT",
    SET_NEW_COMMENT_TEXT: "SET_NEW_COMMENT_TEXT",
    SET_NEW_POST_TEXT: "SET_NEW_POST_TEXT",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_WALL_DATA: "SET_WALL_DATA",
}