export const WALL_ACTIONS = {
    POST_NEW_POST: "POST_NEW_POST",
    POST_NEW_COMMENT: "POST_NEW_COMMENT",
    SET_ARRAY_OF_EXISTING_POST_IDS: "SET_ARRAY_OF_EXISTING_POST_IDS",
    SET_ARRAY_OF_EXISTING_COMMENT_IDS: "SET_ARRAY_OF_EXISTING_COMMENT_IDS",
    SET_ARRAY_OF_COMMENTS: "SET_ARRAY_OF_COMMENTS",
    SET_ARRAY_OF_POSTS: "SET_ARRAY_OF_POSTS",
    SET_COMMENT_POST_ID: "SET_COMMENT_POST_ID",
    SET_NEW_POST_ID: "SET_NEW_POST_ID",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_WALL_DATA: "SET_WALL_DATA",
}